config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'all_jobs' => 'pages#all_jobs'

  resources :jobs
  devise_for :users
  
  root 'pages#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :read, Job
      can :manage, Job, user_id: user.id
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
    extend FriendlyId
    friendly_id :title, use: [:slugged, :finders]
    
    mount_uploader :company_logo, CompanyLogoUploader
    belongs_to :user
    geocoded_by :address   # can also be an IP address
    after_validation :geocode          # auto-fetch coordinates
    validates_presence_of :title, :description, :long_description, :category, :address, :how_to_apply, :company_name, :website, :email, :experience, :working_hours, :compensation
end

app/models/user.rb
class User < ActiveRecord::Base
  
  mount_uploader :logo, LogoUploader
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: [:show]
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    #@jobs = Job.all
    @jobs = current_user.jobs
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.friendly.find(params[:id])
  end

  # GET /jobs/new
  def new
    #@job = Job.new
    @job = current_user.jobs.build
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = current_user.jobs.build(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :company_logo, :description, :long_description, :category, :address, :how_to_apply, :company_name, :website, :email, :experience, :working_hours, :compensation, :slug)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @jobs = Job.all.order("created_at desc").limit(5)
  end
  
  def all_jobs
    @jobs = Job.all.order("created_at desc").paginate(page: params[:page], per_page: 30)
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for(@job) do |f| %>

  <div class="form-inputs">
    <small><em>Add Company Logo</em></small>
    <%= f.file_field :company_logo %><br>
    <%= f.input :title, placeholder: "Job Title, e.g. Front-end developer", label: false, autofocus: true %>
    <%= f.input :description, placeholder: "Short job description...", label: false %>
    <%= f.input :long_description, placeholder: "Long job description...", label: false %>
    <%= f.input :category, placeholder: "Type of work", collection: ['Full Time','Part Time','Contract','Internship','Freelance'], include_blank: false, label: false %>
    <%= f.input :address, placeholder: "Company Address, e.g. 7225 Acorn Avenue, Burnaby BC, V5E 0A9", label: false %>
    <%= f.input :how_to_apply, placeholder: "How to Apply, e.g. Send a resume to jane@company.com", label: false %>
    <%= f.input :company_name, placeholder: "Company Name", label: false %>
    <%= f.input :website, placeholder: "Company Website", label: false %>
    <%= f.input :email, placeholder: "Contact Email", label: false %>
    <%= f.input :experience, placeholder: "Work Experience, e.g. 5 years", label: false %>
    <%= f.input :working_hours, placeholder: "Working Hours, e.g. 40", label: false %>
    <%= f.input :compensation, placeholder: "Compensation, e.g. $20/hour", label: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success" %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Editing Job</h1>

                <%= render 'form' %>
                
                <%= link_to 'Show', @job %> |
                <%= link_to 'Back', jobs_path %>            
        </div>
    </div>
</div>

app/views/jobs/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <h1>My Job Listings</h1>
      <%= link_to 'New Job', new_job_path, class: "btn btn-success" %>
<table class="table table-striped table-hover" style="margin-top: 50px;">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Category</th>
      <th>Address</th>
      <th>How to apply</th>
      <th>Company name</th>
      <th>Website</th>
      <th>Email</th>
      <th>Experience</th>
      <th>Working hours</th>
      <th>Compensation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.description %></td>
        <td><%= job.category %></td>
        <td><%= job.address %></td>
        <td><%= job.how_to_apply %></td>
        <td><%= job.company_name %></td>
        <td><%= job.website %></td>
        <td><%= job.email %></td>
        <td><%= job.experience %></td>
        <td><%= job.working_hours %></td>
        <td><%= job.compensation %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Delete', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<div class="container">
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1>Add a new job <small><%= link_to 'Cancel', jobs_path %></small></h1>
        <%= render 'form' %>        
    </div>
</div>
</div>

app/views/jobs/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-md-2">
               <%= image_tag @job.company_logo.thumb.url, class: "img-rounded" %>
            </div><!-- col-md-2 -->
            <div class="col-md-8">
              <h3><%= @job.title %></h3>
              <h5><%= @job.company_name %></h5>
              <p><small><%= @job.website %></small> | <small><%= @job.email %></small></p>
            </div><!-- col-md-8 -->
            <div class="col-md-2">
              <small style="color: #96a2b2;"><%= time_ago_in_words(@job.created_at) %> ago</small><br>
              <% if (user_signed_in? && (current_user.id == @job.user_id)) %>
                  <% if can? :update, @job %>
                    <%= link_to 'Edit', edit_job_path(@job), class: "btn btn-warning btn-xs" %>
                  <% end %>
                  <%= link_to 'My Listings', jobs_path, class: "btn btn-info btn-xs" %>
              <% end %>
            </div><!-- col-md-2 -->
          </div><!-- row -->
          <div class="row">
            <div class="col-md-12">
              <hr>
            </div><!-- col-md-12 -->
          </div><!-- row -->
          <div class="row">
            <div class="col-md-12">
              <p><%= @job.description %></p>            
            </div><!-- col-md-12 -->
          </div><!-- row -->
          <div class="row">
            <div class="col-md-4">
              <p><%= @job.category %></p>            
            </div><!-- col-md-4 -->
            <div class="col-md-4">
              <p><%= @job.address %></p>
            </div><!-- col-md-4 -->
            <div class="col-md-4">
              <p><%= @job.experience %></p>
            </div><!-- col-md-4 -->
          </div><!-- row -->
          <div class="row">
            <div class="col-md-4">
              <p><%= @job.working_hours %></p>            
            </div><!-- col-md-4 -->
            <div class="col-md-4">
              <p><%= @job.compensation %></p>
            </div><!-- col-md-4 -->
            <div class="col-md-4">
              <p><%= @job.how_to_apply %></p>
            </div><!-- col-md-4 -->
          </div><!-- row -->
        </div><!-- panel-body -->
      </div><!-- panel panel-default-->
    </div><!-- col-md-12-->
  </div><!-- row -->
  <div class="row">
    <div class="col-md-12">
      <p><%= @job.long_description %></p>
    </div>
  </div>
</div><!-- container -->

app/views/layouts/_alert.html.erb
<div class="alert text-center 
    <%= 
    case type.to_sym 
    when :alert, :danger, :error, :validation_errors
        'alert-danger'
    when :warning, :todo
        'alert-warning'
    when :notice, :success
        'alert-success'
    else 
        'alert-info'
    end
    %>
     alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= content %>
</div>

app/views/layouts/_footer.html.erb
<footer style="background-color: black; margin-top: 120px;">
    <div class="row" style="margin:0px;">
        <div class="col-md-12">
            <p>fdffdf</p>    
        </div>
        
    </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Student Jobs', root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
          </li>
        <% else %>
          <li>
          <li><%= link_to 'Register', new_user_registration_path %></li>
          <li><%= link_to 'Login', new_user_session_path %></li>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav' %>
<% flash.each do |type, content| %>
    <% if content.respond_to?('each') 
        content.each do |item| %>
            <%= render 'layouts/alert', 
                type: type,
                content: item %>
        <% end %>
    <% else %>
        <%= render 'layouts/alert', 
                type: type,
                content: content %>
    <% end %>

<% end %>

  
  <%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/all_jobs.html.erb
<div class="container">
    <div class="jumbotron text-center">
      <h1>Browse jobs</h1>
      <p>Use following search box to find jobs that fits you better</p>
      <div style="width:60%; margin: 0px auto; margin-top: 70px;"><form role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Keyword: job title, company, city">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form></div>
    </div><!-- jumbotron -->
    
    <div class="row">
        <div class="col-md-12 text-center">
            <h3 style="color: #333;">Find your dream job!</h3>
        </div>
    </div><!-- row -->
    
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <hr>
        </div>
    </div><!-- row -->
    
    <div class="row">
        <% @jobs.each do |job| %>
    <div class="col-md-12">
        <div class="panel panel-default hover-job">
          <div class="panel-body">
            <div class="row">
                <div class="col-sm-2">
                    <%= image_tag job.company_logo.thumb.url, class: "img-rounded" %>
                </div>
                <div class="col-sm-3">
                    <h3><%= link_to job.title, job %></h3>
                    <h5 style="color: #96a2b2;"><%= job.company_name %></h5>
                </div>
                <div class="col-md-3 col-md-offset-4">
                    <h4><%= job.address %></h4>
                    <% if job.category == 'Full Time' %>
                        <small class="label label-success">Full-Time</small>
                    <% elsif job.category == 'Part Time' %>
                        <small class="label label-warning">Part-Time</small>
                    <% elsif job.category == 'Contract' %>
                        <small class="label label-info">Contract</small>
                    <% elsif job.category == 'Freelance' %>
                        <small class="label label-warning">Freelance</small>
                    <% elsif job.category == 'Internship' %>
                        <small class="label label-danger">Internship</small>
                    <% end %>
                </div>
            </div>
          </div>
        </div>
        
        
    </div>
    <% end %>
    </div><!-- row -->
    
    <div class="row">
        <div class="col-md-6 col-md-offset-3 text-center">
            <%= will_paginate @jobs, class: "pagination pagination-lg" %>
        </div>
    </div>
    
</div>

app/views/pages/index.html.erb
<div class="container-fluid">

<div class="row">
    <div class="col-md-6 col-md-offset-3 text-center">
        <%= link_to 'Post a Job', new_job_path, class: "btn btn-success btn-lg" if user_signed_in? %>
        <%= link_to 'My Job Listings', jobs_path, class: "btn btn-warning btn-lg" if user_signed_in? %>
    </div>
</div>    

<div class="jumbotron text-center">
  <h1>We offer 1,259 job vacancies right now!</h1>
  <p>Find your desire one in a minute</p>
  <div style="width:60%; margin: 0px auto; margin-top: 70px;"><form role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form></div>
</div>
</div>

<div class="container">
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <hr>
    </div>
</div>

<div class="row">
    <div class="col-md-6 col-md-offset-3 text-center">
        <h5>Here's the last five job posted on the website</h5>
        <h2>Recent Jobs</h2>
    </div>
</div>

<div class="row" style="margin-top: 50px">
    <% @jobs.each do |job| %>
    <div class="col-md-12">
        <div class="panel panel-default hover-job">
          <div class="panel-body">
            <div class="row">
                <div class="col-sm-2">
                    <%= image_tag job.company_logo.thumb.url, class: "img-rounded" %>
                </div>
                <div class="col-sm-4">
                    <h3><%= link_to job.title, job %></h3>
                    <h5 style="color: #96a2b2;"><%= job.company_name %></h5>
                </div>
                <div class="col-md-3 col-md-offset-3">
                    <h4><%= job.address %></h4>
                    <% if job.category == 'Full Time' %>
                        <small class="label label-success">Full-Time</small>
                    <% elsif job.category == 'Part Time' %>
                        <small class="label label-warning">Part-Time</small>
                    <% elsif job.category == 'Contract' %>
                        <small class="label label-info">Contract</small>
                    <% elsif job.category == 'Freelance' %>
                        <small class="label label-warning">Freelance</small>
                    <% elsif job.category == 'Internship' %>
                        <small class="label label-danger">Internship</small>
                    <% end %>
                </div>
            </div>
          </div>
        </div>
        
        
    </div>
    <% end %>
</div>


<div class="row" style="margin-top: 30px;">
    <div class="col-md-6 col-md-offset-3 text-center">
        <%= link_to 'BROWSE ALL JOBS', all_jobs_path, class: "btn btn-primary btm-lg" %>
    </div>
</div>


<div class="row">
    <div class="col-md-8">
        <h2>How It Works</h2>
        <p>Pellentesque et pulvinar orci. Suspendisse sed euismod purus. Pellentesque nunc ex, ultrices eu enim non, consectetur interdum nisl. Nam congue interdum mauris, sed ultrices augue lacinia in. Praesent turpis purus, faucibus in tempor vel, dictum ac eros.</p>

        <p>Nulla quis felis et orci luctus semper sit amet id dui. Aenean ultricies lectus nunc, vel rhoncus odio sagittis eu. Sed at felis eu tortor mattis imperdiet et sed tortor. Nullam ac porttitor arcu. Vivamus tristique elit id tempor lacinia. Donec auctor at nibh eget tincidunt. Nulla facilisi. Nunc condimentum dictum mattis.</p>
        
        <p>Nulla quis felis et orci luctus semper sit amet id dui. Aenean ultricies lectus nunc, vel rhoncus odio sagittis eu. Sed at felis eu tortor mattis imperdiet et sed tortor. Nullam ac porttitor arcu. Vivamus tristique elit id tempor lacinia. Donec auctor at nibh eget tincidunt. Nulla facilisi. Nunc condimentum dictum mattis.</p>
    </div>
    <div class="col-md-4">
        <img src="http://shamsoft.net/thejobs/assets/img/how-it-works.png" class="img-responsive">
    </div>
</div>



</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>